### ISSUE TITLE
完全按照readme进行，遇到如下错误，不知道是哪出问题了呢？

### ISSUE THREAD

**Issue by readyFly** [universal-ie/UIE#48]

**Comment by readyFly** [comment]
> Start Data Preprocessing ... Traceback (most recent call last): File "run_uie_finetune.py", line 521, in main() File "run_uie_finetune.py", line 303, in main train_dataset = train_dataset.map( File "/home/miniconda3/envs/uie/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1736, in map transformed_shards = [r.get() for r in results] File "/home/miniconda3/envs/uie/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1736, in transformed_shards = [r.get() for r in results] File "/home/miniconda3/envs/uie/lib/python3.8/site-packages/multiprocess/pool.py", line 771, in get raise self._value KeyError: 'Field "spots" does not exist in table schema'
